# Generated by Django 3.1.3 on 2020-11-15 01:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):


    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agendamento',
            fields=[
                ('id_agendamento', models.AutoField(primary_key=True, serialize=False)),
                ('assunto', models.CharField(max_length=45)),
                ('prioridade', models.CharField(max_length=45)),
                ('duracao', models.IntegerField()),
            ],
            options={
                'db_table': 'agendamento',
            },
        ),
        migrations.CreateModel(
            name='Compromisso',
            fields=[
                ('id_compromisso', models.AutoField(primary_key=True, serialize=False)),
                ('descricao', models.CharField(max_length=45)),
                ('data', models.DateField()),
                ('rotina', models.SmallIntegerField()),
                ('horario', models.DateTimeField()),
            ],
            options={
                'db_table': 'compromisso',
            },
        ),
        migrations.CreateModel(
            name='Tarefa',
            fields=[
                ('id_tarefa', models.AutoField(primary_key=True, serialize=False)),
                ('descricao', models.CharField(max_length=450)),
            ],
            options={
                'db_table': 'tarefa',
            },
        ),
        migrations.CreateModel(
            name='Tripulante',
            fields=[
                ('id_tripulante', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=300)),
                ('contato', models.CharField(max_length=45)),
                ('dt_nasc', models.DateField()),
                ('setor', models.CharField(max_length=100)),
                ('militar', models.SmallIntegerField()),
                ('patente', models.CharField(blank=True, max_length=45, null=True)),
            ],
            options={
                'db_table': 'tripulante',
            },
        ),
        migrations.CreateModel(
            name='FilaEspera',
            fields=[
                ('id_fila_espera', models.AutoField(primary_key=True, serialize=False)),
                ('atendido', models.SmallIntegerField()),
                ('agendamento_id_agendamento', models.ForeignKey(db_column='agendamento_id_agendamento', on_delete=django.db.models.deletion.DO_NOTHING, to='agenda.agendamento')),
            ],
            options={
                'db_table': 'fila_espera',
            },
        ),
        migrations.AddField(
            model_name='agendamento',
            name='agendamento_id_tripulante',
            field=models.ForeignKey(db_column='agendamento_id_tripulante', on_delete=django.db.models.deletion.DO_NOTHING, to='agenda.tripulante'),
        ),
        migrations.CreateModel(
            name='TarefaTripulante',
            fields=[
                ('tarefa_id_tarefa', models.OneToOneField(db_column='tarefa_id_tarefa', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='agenda.tarefa')),
                ('tripulante_id_tripulante', models.ForeignKey(db_column='tripulante_id_tripulante', on_delete=django.db.models.deletion.DO_NOTHING, to='agenda.tripulante')),
            ],
            options={
                'db_table': 'tarefa_tripulante',
                'unique_together': {('tarefa_id_tarefa', 'tripulante_id_tripulante')},
            },
        ),
        migrations.CreateModel(
            name='QuadroTarefas',
            fields=[
                ('tarefa_id_tarefa', models.OneToOneField(db_column='tarefa_id_tarefa', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='agenda.tarefa')),
                ('compromisso_id_compromisso', models.ForeignKey(db_column='compromisso_id_compromisso', on_delete=django.db.models.deletion.DO_NOTHING, to='agenda.compromisso')),
            ],
            options={
                'db_table': 'quadro_tarefas',
                'unique_together': {('tarefa_id_tarefa', 'compromisso_id_compromisso')},
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id_usuario', models.AutoField(primary_key=True, serialize=False)),
                ('senha', models.CharField(max_length=45)),
                ('permissao', models.CharField(max_length=45)),
                ('tipo_usuario', models.CharField(max_length=45)),
                ('email', models.EmailField(default='', max_length=254, unique=True)),
                ('nome', models.TextField(default='', max_length=300)),
            ],
            options={
                'db_table': 'usuario',
            },
        ),
    ]
